[package]
name = "untitled2"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
env_logger = "0.11.8"
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = "0.33.0"
hound = "3.5.1"
rfd = "0.15"
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
serde_json = "1.0.145"